# Generated by Django 3.2.9 on 2021-11-30 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutgoingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("from_name", models.CharField(max_length=255)),
                ("from_address", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("subject", models.CharField(blank=True, max_length=4096)),
                ("text", models.TextField()),
                ("html", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(db_index=True, null=True)),
                ("last_send_attempt", models.DateTimeField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RelatedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.EmailField(max_length=254)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("to", "To"),
                            ("cc", "Cc"),
                            ("bcc", "Bcc"),
                            ("reply-to", "Reply To"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="stored_mail.outgoingmessage",
                    ),
                ),
            ],
            options={
                "unique_together": {("address", "message")},
            },
        ),
    ]
