# Generated by Django 3.2.13 on 2022-05-29 18:47

from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.before_deploy

    dependencies = [
        ("stored_mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingmessage",
            name="discard_after",
            field=models.DateTimeField(null=True),
        ),
    ]
