# Generated by Django 3.2.13 on 2022-05-29 18:49

from django.db import migrations, models
from django_safemigrate import Safe


class Migration(migrations.Migration):
    safe = Safe.always

    dependencies = [
        ("stored_mail", "0003_set_discard_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outgoingmessage",
            name="discard_after",
            field=models.DateTimeField(),
        ),
    ]
