# Generated by Django 3.2.5 on 2021-07-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("admin_login", "Can log into admin site"),)},
        ),
    ]
