# Generated by Django 3.2.5 on 2021-07-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=254)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("sunday", models.BooleanField(default=False)),
                ("monday", models.BooleanField(default=True)),
                ("tuesday", models.BooleanField(default=True)),
                ("wednesday", models.BooleanField(default=True)),
                ("thursday", models.BooleanField(default=True)),
                ("friday", models.BooleanField(default=True)),
                ("saturday", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True, default=0, editable=False
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_generator.calendar",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="SkipDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_generator.calendar",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("calendar", "date")},
            },
        ),
    ]
