# Generated by Django 3.2.5 on 2021-07-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0002_alter_day_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="calendar_generator.calendar",
            ),
        ),
        migrations.AlterField(
            model_name="skipdate",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skips",
                to="calendar_generator.calendar",
            ),
        ),
    ]
