# Generated by Django 3.2.5 on 2021-07-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0005_alter_calendar_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_generator.calendar",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="calendar_generator.day",
                    ),
                ),
            ],
            options={
                "unique_together": {("calendar", "date")},
            },
        ),
    ]
