# Generated by Django 3.2.5 on 2021-07-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0006_resetday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resetday",
            options={"ordering": ["date"]},
        ),
        migrations.AlterField(
            model_name="resetday",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reset_days",
                to="calendar_generator.calendar",
            ),
        ),
    ]
