# Generated by Django 3.2.13 on 2022-05-26 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0008_arbitrarylabel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "width",
                    models.FloatField(
                        default=791,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=612,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "top_margin",
                    models.FloatField(
                        default=36,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bottom_margin",
                    models.FloatField(
                        default=36,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "left_margin",
                    models.FloatField(
                        default=36,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "right_margin",
                    models.FloatField(
                        default=36,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "header_divider_width",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "outline_width",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grid_line_width",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "title_font_size",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "header_font_name",
                    models.CharField(default="HelveticaNeue-Bold", max_length=255),
                ),
                (
                    "letter_font_name",
                    models.CharField(default="HelveticaNeue-Light", max_length=255),
                ),
                (
                    "date_font_name",
                    models.CharField(default="HelveticaNeue-Light", max_length=255),
                ),
                (
                    "title_font_name",
                    models.CharField(default="HelveticaNeue-Bold", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RGBColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "red",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "green",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "blue",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "alpha",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "color",
                "verbose_name_plural": "colors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ColorSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "date_color",
                    models.ForeignKey(
                        help_text="The color used to draw the day of the month, such as 1, 2, 3 ... 31",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "frame_background_color",
                    models.ForeignKey(
                        blank=True,
                        help_text="The color used to draw the background of the whole calendar",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "grid_line_color",
                    models.ForeignKey(
                        blank=True,
                        help_text="The color used to draw the grid lines inside the calendar",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "header_background_color",
                    models.ForeignKey(
                        blank=True,
                        help_text="The color used to draw the background of the header",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "header_divider_color",
                    models.ForeignKey(
                        blank=True,
                        help_text="The color used to draw the lines in between the header (Monday, Tuesday, etc)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "header_text_color",
                    models.ForeignKey(
                        help_text="The color to use to draw the headers: Monday, Tuesday, etc",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "label_color",
                    models.ForeignKey(
                        help_text='The color used to draw arbitrary labels such as "No school"',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "letter_color",
                    models.ForeignKey(
                        help_text='The color to use to "day of the week" letters, such as A, B, and C',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "outline_color",
                    models.ForeignKey(
                        blank=True,
                        help_text="The color used to draw around the outside of the whole calendar",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
                (
                    "title_color",
                    models.ForeignKey(
                        blank=True,
                        help_text='The color used to the title of the calendar, such as "January 2021"',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calendar_generator.rgbcolor",
                    ),
                ),
            ],
        ),
    ]
