# Generated by Django 3.2.13 on 2022-05-27 13:50

from django.db import migrations


def fix_medium_blue(apps, schema_editor):
    """Change medium blue to medium blue"""

    del schema_editor

    RGBColor = apps.get_model("calendar_generator", "RGBColor")

    medium_blue = RGBColor.objects.get(name="Medium Blue")
    medium_blue.red = 0
    medium_blue.green = 0
    medium_blue.blue = 0.803921568627451
    medium_blue.alpha = 1
    medium_blue.save()


def unfix_medium_blue(apps, schema_editor):
    """Change medium blue to its original"""

    del schema_editor

    RGBColor = apps.get_model("calendar_generator", "RGBColor")

    medium_blue = RGBColor.objects.get(name="Medium Blue")
    medium_blue.red = 0.4
    medium_blue.green = 0.803921568627451
    medium_blue.blue = 0.6666666666666666
    medium_blue.alpha = 1
    medium_blue.save()


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0013_auto_20220527_0903"),
    ]

    operations = [migrations.RunPython(fix_medium_blue, unfix_medium_blue)]
