# Generated by Django 3.2.13 on 2022-05-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0017_new_presets"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RGBColor",
            new_name="Color",
        ),
    ]
