# Generated by Django 3.2.13 on 2022-05-27 21:54

from django.db import migrations


def fix(apps, schema_editor):
    """Fix medium blue"""

    del schema_editor

    Color = apps.get_model("calendar_generator", "Color")
    medium_blue = Color.objects.get(name="Medium Blue")
    medium_blue.red = 0
    medium_blue.green = 0
    medium_blue.blue = 0.803921568627451

    medium_blue.save()


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0018_rename_rgbcolor_color"),
    ]

    operations = [migrations.RunPython(fix, migrations.RunPython.noop)]
