# Generated by Django 3.2.13 on 2022-05-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0019_fix_medium_blue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="color",
            options={"ordering": ["name"]},
        ),
    ]
